swagger: "2.0"
info:
  description: swagger for microservices
  title: swagger

paths:
  /register:
    post:
      tags:
        - User
      summary: registration
      description: user registration
      parameters:
        - name: body
          in: body
          schema:
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description:
            Response

  /activate/{token}:
    get:
      tags:
        - User
      summary: activation
      description: activating user
      parameters:
        - name: token
          in: path
          type: string
      responses:
        200:
          description:
            Response