swagger: "2.0"
info:
  description: "This is a sample server Microservices server.  You can find out more about Swagger at
                [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/)."
  version: "1.0.0"
  title: "Swagger Microservices"
tags:
- name: "note"

post:
  /note/create:
    summary: create note
    description: create note flask_service
  parameters:
    - name: token
      in: header
    - name: body
      in: body
      schema:
        properties:
          title:
            type: string
responses:
  200:
    description:
      Response

get:
  /note/read:
    summary: read note
    description: reading note by id
  parameters:
    - name: token
      in: header
response:
  200:
    description:
      Response

put:
  /note/update/{pk}:
    summary: update note
    description: create update note API
  parameters:
    - name: token
      in: header
    - name: pk
      in: path
      type: integer
    - name: body
      in: body
      schema:
        properties:
          title:
            type: string
          description:
            type: string
          color:
            type: string
respons:
  200:
    description:
      Response

delete:
  /note/delete/{pk}:
    summary: delete note service
    description: delete note service using note flask_service
  parameters:
    - name: token
      in: header
    - name: pk
      in: path
      type: integer
res:
  200:
    description:
      Response