swagger: "2.0"
info:
  description: "This is a sample server Microservices server.  You can find out more about Swagger at
                [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/)."
  version: "1.0.0"
  title: "Swagger Microservices"
tags:
- name: "user"

post:
  /user/register:
    summary: user registration
    description: register user using flask_service
  parameters:
    - name: body
      in: body
      schema:
        properties:
          username:
            type: string
          email:
            type: string
          password:
              type: string
responses:
  200:
    description:
      Response

get:
  /user/activate/{token}:
    summary: activate user
    description: activate user using flask_service
  parameters:
    - name: token
      in: path
      type: string
response:
  200:
    description:
      Response

put:
  /user/reset/{token}:
    summary: reset user password
    description: create reset password user flask_service
  parameters:
    - name: token
      in: path
      type: string
    - name: body
      in: body
      schema:
        properties:
          email:
            type: string
          old_password:
            type: string
          new_password:
            type: string
respons:
  200:
    description:
      Response